### ISSUE TITLE
biostar.wsgi

### ISSUE THREAD

**Issue by vittel1** [ialbert/biostar-central#319]
When I try to start gunicorn.start.sh I get this:

"ImportError: No module named biostar.wsgi"

What does it mean? 

In this data it says: 

# The WSGI module that starts the process.
DJANGO_WSGI_MODULE='biostar.wsgi'

But I haven't go it?!

**Comment by ialbert** [comment]
It means that the biostar folder is not on the python import path of your process. 

Make sure to study in detail the django deplyoment processes and rest assured that the Biostar system provides you with everything you need since it is being used for many years. 

On the other hand setting up correctly apache mod_wsgi other systems is outside the support with can provide here. Alas that can be a very frustrating process too. I would recommend the stackexchange sites to post setup questions to.
