### ISSUE TITLE
ldap integration

### ISSUE THREAD

**Issue by david-gang** [ialbert/biostar-central#329]
Hi all,

Can biostar be integrated with ldap?

Thanks,
David

**Comment by ialbert** [comment]
it is probably no overly complicated using something like django-ldap

https://pypi.python.org/pypi/django-auth-ldap/1.2.5

**Comment by david-gang** [comment]
Thanks for the quick answer.

**Comment by gnomics** [comment]
I've configured live/deploy.py with django-auth-ldap according to [these instructions](http://www.spannerbracket.com/wordpress/?p=40) but it's still not working.  Is settings.py the only place in biostar-central that would need to be modified or does integration also require modification of biostars/apps/users/view.py and/or the account.login.html template?

**Comment by ialbert** [comment]
well, I have never set this up so I couldn't tell right away, I would start by remapping the login url to a new view that uses ldap, the current view routes through django_allauth

**Comment by gnomics** [comment]
Thanks for the pointer!  I can now authenticate biostar against Active Directory after implementing the [user_login](http://www.tangowithdjango.com/book17/chapters/login.html) view described in the Tango with Django tutorial.

**Comment by liewjx** [comment]
Hi gnomics, is the user_login view function implemented in biostars/apps/users/view.py? Are there any other changes that needs to be made besides these?

**Comment by Spannella** [comment]
@gnomics Could you share your solution to this? I am attempting to add LDAP support for my users.

**Comment by Djones4822** [comment]
Hi, I'm looking into this now and wanted to share some findings. I'm going to list my findings in no particular order, I plan on applying these tomorrow (or possibly later this week). 

1. update `/accounts/auth.py` to update the `verify_login` to use the django ldap package [here](https://django-auth-ldap.readthedocs.io/en/latest/authentication.html). 

2. Further modify `verify_login()` to check if the authenticated user exists in the `User` table, and to create it if not. Possibly edit the `user_signup()` function in `/accounts/views.py`... Looks like django provides an option for populating the user model before authentication, see [here](https://django-auth-ldap.readthedocs.io/en/latest/users.html#updating-users)

3. Eliminate the User table check that happens before the verify_login in `/accounts/views.py` `user_login()`, possibly replace with an anonymous bind check?

4. Remove the signup button and the password reset button on the `/forum/templates/accounts/login.html` page. Also possibly remove the signup and reset pages entirely in order to remove them from the directory (maybe a better way to do this...). Are there more reference to "Register" that need to be removed? 

Maybe more... if I find more things during my delve I will share. @ialbert if you have any advice I would greatly appreciate it. Thanks,

-Dave
