### ISSUE TITLE
Alternative "reply by email" implementation

### ISSUE THREAD

**Issue by llaisdy** [ialbert/biostar-central#332]
Dear All

I'm doing "reply by email" in a slightly different way from that suggested in the Biostars docs.  I'd like to paraphrase the documentation and outline this alternative method --- in case either I don't understand the documentation or the method I'm using is worse.

Please advise.

The documentation [1] has:

> ... For example when delivering email via postmaster utility on
> linux the etc/alias file would need to contain:
> 
>     reply: "| curl -F key='123' -F body='<-' https://www.mybiostar.org/local/email/

[1] http://docs.biostars.org/en/latest/install.html#receiving-emails

(I assume that's a typo and there should be a closing '"'.)

The effect of this is that, when the server receives an email to reply[...]@mybiostar.org it will send out the email as the body of a http POST request to /local/email/.

The site I'm building is not a public site, and all the urls apart from login are @login_required.  It seems to me that the above method of submitting emails would need some extra work to submit past any authentication test.

The method I'm using is to keep the email on the server and use postfix et al. to send it locally to the site user and have it piped to a site management command.  Effectively:

    " | python manage.py handle_email  --settings=biostar.settings.base "

(with all paths resolved properly)

This seems to be working, it avoids opening up a url, and it frees up the django frontend a little bit.

What are the reasons against this method?  I suppose it spins up another python process for every email, in which case some kind of queueing or pooling might be a good idea.

With thanks and best wishes

Ivan

**Comment by ialbert** [comment]
The local/email handler will only process emails that have a valid reply
token. Hence only users that have already created an account can generate a
post. So that url does not need to be protected with @login_required.

I think the easiest way to handle email (and this will be the default setup
in Biostar 3.0) is to handle it via a mail transaction agent like Mailgun.
There are a few other alternatives that also have fairly generous free
plans (but even the paid plans are cheap). All other setups require a more
in depth understanding and interfacing with the actual mail handling agent
which I found to be quite the extra workload to set up and document.

Your case should work - but it has a substantial overhead as it starts up
not only python (that alone is not a big dea unless you had dozens of
emails per minute) but beyond python it bootstraps a good chunk of the
whole django site, models etc. That may be too much work to do on every
email - so as you suggest perhaps limiting and pooling it for once a minute
or every five minutes would be better.





On 19 March 2015 at 05:13, Ivan Uemlianin <notifications@github.com> wrote:

> Dear All
>
> I'm doing "reply by email" in a slightly different way from that suggested
> in the Biostars docs. I'd like to paraphrase the documentation and outline
> this alternative method --- in case either I don't understand the
> documentation or the method I'm using is worse.
>
> Please advise.
>
> The documentation [1] has:
>
> ... For example when delivering email via postmaster utility on
> linux the etc/alias file would need to contain:
>
> reply: "| curl -F key='123' -F body='<-' https://www.mybiostar.org/local/email/
>
>  [1] http://docs.biostars.org/en/latest/install.html#receiving-emails
>
> (I assume that's a typo and there should be a closing '"'.)
>
> The effect of this is that, when the server receives an email to
> reply[...]@mybiostar.org it will send out the email as the body of a http
> POST request to /local/email/.
>
> The site I'm building is not a public site, and all the urls apart from
> login are @login_required. It seems to me that the above method of
> submitting emails would need some extra work to submit past any
> authentication test.
>
> The method I'm using is to keep the email on the server and use postfix et
> al. to send it locally to the site user and have it piped to a site
> management command. Effectively:
>
> " | python manage.py handle_email  --settings=biostar.settings.base "
>
> (with all paths resolved properly)
>
> This seems to be working, it avoids opening up a url, and it frees up the
> django frontend a little bit.
>
> What are the reasons against this method? I suppose it spins up another
> python process for every email, in which case some kind of queueing or
> pooling might be a good idea.
>
> With thanks and best wishes
>
> Ivan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ialbert/biostar-central/issues/332>.
>



-- 
Istvan Albert
Associate Professor, Bioinformatics
Pennsylvania State University
http://www.personal.psu.edu/iua1/

**Comment by llaisdy** [comment]
Thanks.  Mailgun looks good for price and usability.  Worth considering.
