### ISSUE TITLE
site = site = ... typo?

### ISSUE THREAD

**Issue by llaisdy** [ialbert/biostar-central#336]
Dear All

Is this line a typo or is there a reason for repeating site?  My python is a bit basic

```python
site = site = Site.objects.get_current()
```

https://github.com/ialbert/biostar-central/blob/master/biostar/server/management/commands/digest.py#L23

Thanks

Ivan

**Comment by ialbert** [comment]
just a typo.

**Comment by llaisdy** [comment]
Thanks :)

Are digests working in current biostar?  (I'm trying it out now)

And/or are digests being heavily refactored for biostar3?  (I haven't been able to find digest-related code in the 3.0 branch).

Ivan

**Comment by ialbert** [comment]
the digests did never quite make it in - I could not decide what the right course of abstraction was but the user options are in there and one could  write a a simple script that looks at the site stats via the API and generates an email out of those.

I will try to add digests into 3.0 though and launch 3.0 with that functionality.

**Comment by llaisdy** [comment]
digest.py does seem something of a work-in-progress.

I am planning (today) to work on it and use it from cron or celery.  I'll make the "send" parameter optional and without it the script will filter through all users.  Did you hit any snags, or did time run out?

Thanks

**Comment by llaisdy** [comment]
So, it's more or less working.  If you might be interested in using it, I've had approval to release this digest.py module.  Let me know and I'll upload it to my fork and send a PR.

Ivan

**Comment by ialbert** [comment]
That would be nice, I would take a look since this I need some ideas.

Actually I forgot to mention a really cool new email sending functionality that went into Biostar 3.  It allows you to place the email subject, plaintext and html version of the same email into a single template. It then extracts the blocks corresponding to each section.

Helps a lot with keeping the information in one file.

        data = dict(name="John Doe", content="world")
        em = EmailTemplate("mailer/mailer_test.html", data=data)
        em.send_email(from_email="foo@com", to=["bar@com"])

The template is here:

https://github.com/ialbert/biostar-central/blob/3.0/biostar3/forum/templates/mailer/mailer_test.html

Tests:

https://github.com/ialbert/biostar-central/blob/3.0/biostar3/forum/tests/test_mailer.py

and the code is here:

https://github.com/ialbert/biostar-central/blob/3.0/biostar3/forum/mailer.py

**Comment by llaisdy** [comment]
That is a very good idea! --- I've just spent some time making sure daily_digest.txt and daily_digest.html are in sync.  

I'll tidy up my code and send a PR in the next day or so.

Best wishes

Ivan
