### ISSUE TITLE
Requests: Suggestions for 3.0

### ISSUE THREAD

**Issue by sbagmeijer** [ialbert/biostar-central#381]
I had some requests for the new 3.0 if possible.

1): Could you perhaps add the "Battle.net" login as a possible sign up option?
https://dev.battle.net/docs/read/oauth

2): Google analytics, I think it is not there anymore could this be added back?
(Did add this myself with use of google submitted the code: #382)

3): Cookie warning, in the EU we have some new weird law that we must let people accept if the website uses cookies is this something that could be added?

4): (not sure if this is already there but could not find it) Like buttons for Facebook, Twitter and Google, perhaps in the right under the posters name box we could have 3 small buttons so people could share the post on social media.

5): Sitemap function.

---
Small issue:
Not sure if this is intended or a issue with the template but I noticed that the current "vote" and "bookmark" button make the post slightly misinformed in the top if you look this post for example:
https://test.ulyaoth.net/p/10/

You see in the top everything goes slightly right and then the other text under the buttons, maybe a idea would be to move those buttons to the right under the posters name?

**Comment by ialbert** [comment]
We use a third party library for authentication this is their list of providers:

http://django-allauth.readthedocs.org/en/latest/providers.html

Adding a new provider doable I believe one of our collaborators contributed the ORCID integration back to the library.

We'll add sitemaps.

Cookie warning should be added to the base template we don't have to have that so it is waiting for someone that feels the pain.

The alignment works that way because once the content is large the votes float to the left and the text wraps around them, it would be a lot of wasted space if that was a full vertical box. This is especially important once the site is browsed on a smaller screen.

**Comment by sbagmeijer** [comment]
I have one more question I will add it here instead of keep opening more topics.

So Basically I have the "Site" Function working now:
https://test.ulyaoth.net and https://tutorials.ulyaoth.net

They show different content, now what would you suggest if I go one step further and I want to use the domain "ulyaoth.jp" for Japanese content? Should I simply setup a whole new separate instance for this domain or make a site also for this? 

And if I would only keep it in one site how can I do domain specific settings? So Basically when someone is on "ulyaoth.net" and post something new I want the "Site" dropdown menu only show English stuff and post to "ulyaoth.net" but when someone is on the Japanese site I want them to see the dropbox in Japanese and post to "ulyaoth.jp".

If this is not possible and I need to use different installations is there a way to keep the user database the same atleast?

**Comment by ialbert** [comment]
In principle one can do anything they want with the domains because typically the site is run through a frontend (proxy) webserver like nginx and biostar runs in a separate process that gets requests from the proxy. The proxy can then decide where to send the requests and even what domain the server sees on the other side. So any domain could be proxied to say look like a biostar subgroup. But setting this up will require some level of system admin and management expertise.

You do bring up an interesting point of wether this could be supported in a global way from Biostars and that is possible too, just I have not thought about it.

For your particular case though I would say mixing languages  on the same forum can make them less popular. When you run a subdomain of biostars it is still the same site and some content will still be shared (help, faq, etc). That would be weird to have in two languages.

You can reuse the same database of course but that would really lead to the same situation.

**Comment by ialbert** [comment]
Continued here https://github.com/ialbert/biostar-central/issues/400
