### ISSUE TITLE
posts.models.Tag and users.models.Tag - why both?

### ISSUE THREAD

**Issue by llaisdy** [ialbert/biostar-central#394]
Dear All

Why does the users app have its own Tag model?  

The model is used for a user's watched tags, and these tags are "semantically" the tags from the posts app - i.e. the tags that a Post is tagged with.

Why is users.models.Tag needed? (with its separate db table)

Thanks

Ivan

**Comment by ialbert** [comment]
It is not used, at some point I considered allowing users to tag themselves as belonging to groups,  but that has not been implemented.

**Comment by llaisdy** [comment]
How do you mean it is not used? The db table is created (users_tag), users' watched tags are stored there.

**Comment by ialbert** [comment]
oh ok my bad, I confused it with the version that is not yet released. that works differently.

in this case it has a separate tag table because I wanted to decouple it from the other app.

In general (here and elsewhere) I found that this decoupling is not a good idea as it leads to additional complexity.
