### ISSUE TITLE
Feature request: prevent user from asking a new question ...

### ISSUE THREAD

**Issue by lindenb** [ialbert/biostar-central#397]
Hi all,

a feature request: give the admins the right to prevent a user from asking a new question if he previously asked some questions but they were never commented or validated. 

Thanks,

**Comment by ialbert** [comment]
The problem here is that we also need to add a feature that informs and explains this to the user in a way that they understand. That is a lot work to do an maintain over the future.

Then having one person state to another "you cannot talk until you do this or that" can be perceived very negatively. Perhaps the user has a different and perfectly valid question next etc.

I am planning to add a different feature, that of a "draft" or "submission". This is a post that is submitted (posted) but will only appear publicly once moderators "endorse" it. It is like a quick and easy review process.
