### ISSUE TITLE
not showing notifications on web

### ISSUE THREAD

**Issue by martenson** [ialbert/biostar-central#405]
At https://biostar.usegalaxy.org/ (running 16.03) I do no longer see the highlights (and numbers) on Messages and Votes in the menu that used to show how many notifications are under each item. I have to click on them to see the list and the new items are properly highlighted there.

**Comment by ialbert** [comment]
The way this works may occasionally feel counterintuitive.

The new messages on the navigation tab shows how many new messages/votes one received  since their last "visit" to Biostar (any page). 

The "green" highlight  on the messages/votes page indicate new elements relative to visiting that particular  page.

Basically the navigation tabs show recent activity that relates to the user account and not a summary of everything. 

The goal is that if someone does not want to visit their new messages then tomorrow we will only show them the new things that happened since their last visit, but on the messages tabs we will show everything.

**Comment by martenson** [comment]
I might have described it confusingly. The recent activity is not shown to me i.e. `Messages` and `Votes` are never highlighted even though there are new Messages and new Votes since my last visit (I see them highlighted in the list when I click on the menu item)

**Comment by ialbert** [comment]
OK let me investigate.

**Comment by ialbert** [comment]
Can you check with others to see if this happens there as well.

**Comment by martenson** [comment]
I will.

**Comment by martenson** [comment]
I confirmed this with @davebx - I voted on his answer and he did not see the notification on his next visit. 

Is visit tied to a session?

**Comment by ialbert** [comment]
To test this properly have them log off, vote on their answer then have them log back in. The visit is indeed tied to the session and you'd  only get the notification once the session expires (10 minutes I think, depends on settings).

**Comment by ialbert** [comment]
go vote on this then I can test what is going on

https://biostar.usegalaxy.org/p/7686/#7700

**Comment by martenson** [comment]
@ialbert voted

**Comment by ialbert** [comment]
The vote did show up in the navbar.

**Comment by martenson** [comment]
:(
I will keep an eye on it and investigate more precisely when it happens

**Comment by ialbert** [comment]
I think (hoping really) that there is no bug - it is just that occasionally looks incorrect since the highlighting  is not in real time but chunked by 10 minutes.  

For example you check your votes highlight goes off, then you go to another page.

Suppose you get a new vote right there, highlight will still be off for 10 more minutes but if you go to your votes it shows you the new vote there.

But now you wait 10 minutes, the highlight goes on. But suppose you don't visit the votes page again then after 10 minutes the highlight goes off again.

**Comment by martenson** [comment]
I remember having backlog of messages for 2 weeks not being highlighted. I will investigate and let you know in this thread. Thanks!

**Comment by martenson** [comment]
An example of a sequence of clicks. Is this how the notifications are supposed to work? @ialbert 

Arrive at Biostar
![screenshot 2016-04-29 15 38 02](https://cloud.githubusercontent.com/assets/1814954/14927522/76166264-0e20-11e6-96c9-6f84aa551293.png)

Click "Votes"
![screenshot 2016-04-29 15 38 07](https://cloud.githubusercontent.com/assets/1814954/14927525/7a270b74-0e20-11e6-9a4d-3ba84f42ea6a.png)

Click "Messages"
![screenshot 2016-04-29 15 38 17](https://cloud.githubusercontent.com/assets/1814954/14927528/7cc7172a-0e20-11e6-95e0-907f42a30913.png)

**Comment by RamRS** [comment]
@martenson That is pretty much how I have seen them work ever since I joined the sites.

**Comment by ialbert** [comment]
Yes, this is how it was designed to work - though I do agree that it can occasionally look like there is an inconsistency - for example the message shows 2 new messages but you have actually three new messages on your page when you visit it.

This is because when you logged in you only had two new messages, but upon login an asynchronous  background thread fires up that checks for badges. While you were browsing to another page the thread determined that you go also got a badge, and that produced a third message, so now you have three messages but there is not live push or actually update the message count and that still shows 2 would show the same number for 10 more minutes. After 10 minutes the new message counter would show 1 new message. Basically that new message that you got in the background. 10 more minutes later if nothing else happened you would be shown no new messages.

This is by design actually. While using the site as a power user I disliked when the site was too eager to tell me what is new - it felt I like it is interrupting me. If you are an active user with many threads going, the  live counters would go crazy, basically you get a new message after every page refresh and that can feel overwhelming,  that is very desensitizing, after a while you don't care the new messages.  The 10 minute intervals slow down time and give people short summaries of what happened and allows people to feel that they have caught up.
