### ISSUE TITLE
English only validator for Title field

### ISSUE THREAD

**Issue by paulokopny** [ialbert/biostar-central#407]
Current version has an "english only" validator for the Title field:

https://github.com/ialbert/biostar-central/blob/master/biostar/apps/posts/views.py#L93

Was it introduced for some important reason? It broke a bit our forum as we migrated from older version of biostars and we have a lot of posts with titles in Russian. Fixed the problem by removing the validator, yet still wondering why it is there.

**Comment by ialbert** [comment]
The spam got really bad and was all in foreign language - hence we put that in as a damage mitigation. Then it seemed to help a lot and was kept. You can add multiple languages to the detection.

See also this  there:

https://github.com/ialbert/biostar-central/commit/75acf83705e20a67ba4a8f0679e2ae58d1089a4d

**Comment by paulokopny** [comment]
I altered the code for our instance, but I don't really think this is the way to do it.

Maybe validators for each field should be configurable (and plugable), so a user would be able to enable "English only" mode, or a filter for swear words, for example?

**Comment by ialbert** [comment]
I do agree with the sentiment but this was added as purely as a protection against spam and turned out to work well for that.

Adding a more pluggable interface to it feels too much effort as it is really not about adding utility to the site but to protect against abuse. Some/many sites won't need this feature at all.

A much better alternative is to strengthen the spam protection - but that is a lot harder to do without raising the cost of using the site.
