### ISSUE TITLE
checkbox to accept response as answer does not appear in Safari browser

### ISSUE THREAD

**Issue by malcook** [ialbert/biostar-central#439]
For at least this user, switching to firefox allowed seeing the checkbox:  https://support.bioconductor.org/p/99375/#99813

**Comment by ialbert** [comment]
I do see that widget it in Safari - so it would need to be confirmed by others.

**Comment by hsinyenwu** [comment]
I was the one cannot see the checkbox. My safari is 10.1.2 and my OS is MacOS Sierra 10.12.6.

The top browser is Safari and the one below is Firefox. You can see the difference. Thanks!
<img width="1280" alt="firefox" src="https://user-images.githubusercontent.com/4383665/29846525-3dfb66e6-8ce5-11e7-8434-edd3c0f76f71.png">

**Comment by ialbert** [comment]
The site offers different views at different browser window resolutions so that it works well on phone and tablets withouth showing all the features on those intergfaces. In this case the source of the discrepancy is that your Safari browsers is smaller and is on the other side of the cutoff. 

Drag the window for your Safari browser to make it a bit wider and you'll see that "accept widget" pop into view.

**Comment by hsinyenwu** [comment]
Thanks, ialbert. You are absolutely right.
