### ISSUE TITLE
Issue posting comments to the site just now

### ISSUE THREAD

**Issue by mdshw5** [ialbert/biostar-central#444]
I just tried to comment here (https://www.biostars.org/p/280246/) but after two failed attempts (no error message - just said "your comment was posted") I added an answer. I'm not sure if this is affecting other users or other questions.

**Comment by wdecoster** [comment]
I see your comment, twice.

**Comment by ialbert** [comment]
There is some issue that I need to investigate. Some internal process scales incorrectly and that can stall the response for a bit. Perhaps it is the message sending. This few second stalling is what leads to confusion (and resubmits).

As the site grew past the quarter million posts it is now starting to manifest itself.

Because it involves some sort of scaling problem it went unnoticed for a while.

**Comment by ialbert** [comment]
I have added a change that ought to speed up the response. A bigger and better fix will follow later.

**Comment by mdshw5** [comment]
Thanks for the attention. It still appears to take multiple minutes for comments to show up, but I'm patient :)

**Comment by ialbert** [comment]
That is really weird, I posted a comment and I see it instantly, no delay whatsoever.
Could someone else here test a comment on this:
https://www.biostars.org/p/280246/#280795

**Comment by ialbert** [comment]
I have asked someone else to post a comment in this thread and they saw the comment appear instantly (fraction of a second) as well.

**Comment by genomax** [comment]
Perhaps Matt is responding using email instead of posting directly from website?

**Comment by mdshw5** [comment]
Nope. I was just lying a bit. I didn't wait for my comment to appear, but assumed it would eventually post. It turns out Safari 11.0 does not render the comments on Biostars:

![screen shot 2017-10-31 at 4 44 20 pm](https://user-images.githubusercontent.com/819554/32248030-bfe38638-be5a-11e7-9949-410f6573d11e.png)
