### ISSUE TITLE
urls between parentheses incorporate closing parenthese

### ISSUE THREAD

**Issue by wdecoster** [ialbert/biostar-central#445]
When a url is posted in a comment/post between parentheses like (http://saureus.beta.mlst.net/) the final parenthese is considered "part of the URL and will, obviously, return a 404. A solution is to add a space between the url and the closing parenthese,  e.g. (http://saureus.beta.mlst.net/ )

It does work fine here on github, I've seen the issue multiple times on biostars, e.g. https://www.biostars.org/p/283965/#283995 (I fixed it already...)

I can't figure out where the code is for recognizing urls - if you could point me in the right direction I'd be happy to take a look, caveat: I haven't worked with django...

**Comment by ialbert** [comment]
Yes, this is a known issue that I thought I fixed myself and it comes from bleach.linkify.

https://github.com/mozilla/bleach/issues/190

The linkifying process itself gets applied in:

https://github.com/ialbert/biostar-central/blob/master/biostar/apps/util/html.py#L141

I thought that this was fixed, apparently not fully, though this problem is a bit more complicated in our case - perhaps the library is still the wrong version. I will look into this.

**Comment by wdecoster** [comment]
Would it be a (nasty?) fix to remove a trailing parenthesis from an identified uid? `.rstrip(")")`

`emb_patt = '<a href="%s">%s</a>' % (uid.rstrip(")"), uid)`

**Comment by ialbert** [comment]
Yes, actually that would be an easy fix. Hacky but really simple. I like that ;-)

I'll try to add this later today once I get in.

**Comment by wdecoster** [comment]
Having a trailing slash followed by a parenthesis results in this url "http://saureus.beta.mlst.net/)". The same url without the trailing slash indeed does not incorporate the parenthesis.

But is there ever a valid url ending in a parenthesis?

**Comment by ialbert** [comment]
yes, parentheses in links are very common in wikipedia for example, see:

https://en.wikipedia.org/wiki/Test_(assessment)

so technically speaking the ending `)` is valid. In practice (and that is what I pointed out in the issue bleach issue 190 above), both parentheses are included and we are safe to remove the trailing one if the opening one was outside the link. But you see how that complicates the picture.

Now the fix I submitted to bleach (and the bugfix was to make Biostars work properly) appears to not apply correctly when there is a trailing slash to the URL. An oversight - so that is the bug that needs to be fixed.

**Comment by wdecoster** [comment]
Another hack I can think of is to test if the url is valid - i.e. see if it returns a 404. If not, don't touch it. If it does, try to fix. This does probably less damage - and the corner case that a url exists both with and without trailing slash/parenthesis is negligible.

**Comment by ialbert** [comment]
Checking a website may hang the site - it is unpredictable how long accessing another website might take - so it would block the post appearing - leading to other problems. I think fixing the pattern should be the most beneficial and contributing that fix back to bleach. I'll look into this.

**Comment by Natay** [comment]
This issue has been fixed
