### ISSUE TITLE
Feature request: link to github profile

### ISSUE THREAD

**Issue by wdecoster** [ialbert/biostar-central#446]
Currently it's possible to specify a website in the user profile.  
But wouldn't it be nice to also have a field for a link to our GitHub profile?

Obviously it's possible to put that in your biography, but it would just feel neater to have a designate field for this, just like the twitter and google scholar field.

**Comment by ialbert** [comment]
Well, one could list their GitHub account in the website field that you mention above.

With this feature, we have to recognize that the majority of users on Biostars will not have their own GitHub repo (at least not one they would want to be prominently featured). 

What I do think would be more helpful is to integrate the two sections better. So that the bio and web links are not so far away from one another.

We are planning on having a new interface in early 2018. So we will close this for now - but we'll take note of the issue.

**Comment by wdecoster** [comment]
> Well, one could list their GitHub account in the website field that you mention above.

Right, but I have both a website and a GitHub profile

> we have to recognize that the majority of users on Biostars will not have their own GitHub repo

And the same is true for a twitter account.

**Comment by ialbert** [comment]
Now that I thought about it more the right solution seems to be to add a parser step that recognizes the link that someone lists in their bio. So if a user has a github link in the bio, it produces a github logo and link under their name, if they have a twitter link does so for twitter. If they have both, it produces both etc.

That way we don't have to predetermine the fields in the database. Right now adding a new field requires a full data migration because it is a field is represented as a database column. Among the many things, it means stopping the database and applying the change. It holds back progression. Not surprisingly we all prefer to avoid database migrations since other things can go bad and affects the entire site.

Whereas adding a parser is a more lightweight solution and can be expanded with code rather than via data alteration.  I will label this as a feature request for the new interface - will follow up here once we get closer to deploying that.

**Comment by wdecoster** [comment]
> Right now adding a new field requires a full data migration because it is a field is represented as a database column. Among the many things, it means stopping the database and applying the change. It holds back progression. Not surprisingly we all prefer to avoid database migrations since other things can go bad and affects the entire site.

Ah, was not aware of this. Indeed, your suggested approach makes things much more flexible.
