### ISSUE TITLE
unable to search

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#515]
Hi.
I created some posts, but unable to search them. Do you have any idea?
Thank you.
![image](https://user-images.githubusercontent.com/55419584/69584809-b1661580-1010-11ea-9cd0-73fabc724cf9.png)

**Comment by piggybit** [comment]
Is there any guideline for connection with Postgresql?
Thanks.

**Comment by Natay** [comment]
We use whoosh to search. This requires an index to search, without it you get no results. 
To create the index, run `make reindex`. 
Here is the whoosh docs for more reference : https://whoosh.readthedocs.io/en/latest/

Since we are using Django, you can refer to their docs on how to connect to Postgresql.
Here is the Django docs on postgres: https://docs.djangoproject.com/en/2.2/ref/databases/#postgresql-notes

**Comment by piggybit** [comment]
thank you Natay, we can close.
