### ISSUE TITLE
Non-staff cannot post new post

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#524]
Hello.

I am not sure if this is a bug or not, but seems non-staff user, piggy, cannot post new post, while i use super admin and can easily post post without any error.
Could you assist here @Natay ?

Thank you very much.

![Screenshot from 2019-12-13 18-42-19](https://user-images.githubusercontent.com/55419584/70798126-afee6880-1dd8-11ea-80ba-372338ba10e6.png)
![Screenshot from 2019-12-13 18-42-39](https://user-images.githubusercontent.com/55419584/70798132-b2e95900-1dd8-11ea-835c-f30cfd378aff.png)

**Comment by Natay** [comment]
@piggybit Thanks for the report.

This issue comes from our recapthca field being unnecessarily required even when the key was not set in `settings.py`. This error was trigged when untrusted users tried to post something without a recaptcha key, since it was not given in the `setting.py`. It works for staff/admin because they are not required to fill out the recaptcha on post create.

We fixed it so the default works without a recapthca key in the settings.

We use django-recaptcha2 , here is some reference on how to set up your recaptcha settings: https://github.com/kbytesys/django-recaptcha2

**Comment by piggybit** [comment]
thank you for your explanation and fix, Natay.
Really appreciate it!
