### ISSUE TITLE
auto reindex?

### ISSUE THREAD

**Issue by piggybit** [ialbert/biostar-central#555]
Happy New Year!
I wondering if we can auto re-index whenever we have new post?

Thanks.

**Comment by Natay** [comment]
Happy New Year.

Auto re-indexing is only enable when the server is run asynchronously. This is done by having a uwsgi timer that runs every 5 mins to index new posts. 

However, this is going to be changed since the uwsgi timer causes problems when running along side a logger. 

This issue with the timer is further described here: https://github.com/unbit/uwsgi/issues/1369

**Comment by piggybit** [comment]
Thanks Natay for sharing this.
Is there any plan for a migration from uwsgi timer?

**Comment by Natay** [comment]
Yes, we are migrating to crontab as a way to schedule tasks. 

Here is more info on crontab : http://man7.org/linux/man-pages/man5/crontab.5.html

**Comment by ialbert** [comment]
Some jobs, especially reindexing should ONLY be run in  crontab so that potentially parallel processes don't break the index. I don't think the Whoosh index can deal with two processes indexing it at the same time. There is a task called index invoke as

    python manage.py index 

that will reindex new posts.

 At the same time there are a lot of tasks that cannot, mostly asynchronous tasks, computing awards, user location etc. that cannot run in crontab. These will need to work in uwsgi. 

If  the logging module breaks uwsgi, then the solution is is that we need to remove (or turn off) the Python based logging within these tasks, and will have to just print the logging message instead.  Alternatively a different task queue needs to be used.
