### ISSUE TITLE
Updated information takes time to get reflected (my tags/bookmarks/my post)

### ISSUE THREAD

**Issue by djangotestapp** [ialbert/biostar-central#640]
my tags/bookmarks/my post are not getting updated immediately and takes about 4mins approx. for getting displayed. Is this an issue or can it be configured in such a way that these can be updated & displayed immediately?

Thanks in Advance.

**Comment by Natay** [comment]
Thanks for letting us know, this issue comes from the pagination cache. 

To clarify more, do new posts that you create immediately appear at the top when clicking 'my posts'?

**Comment by djangotestapp** [comment]
@Natay retried the same again by creating multiple posts. The new posts are appearing at the top while selecting 'my posts' without any issues now. But the recently added  'my tags', 'bookmarks' and also the 'following' posts are taking few minutes to appear.But sometimes its getting displayed immediately. Not sure about the reason behind this.

**Comment by ialbert** [comment]
This has to do with the way default pagination in Django works, the `count` operation in a database will take very long time when there are lots of items. You can read more about the problem here:

https://hakibenita.com/optimizing-the-django-admin-paginator

we have made a cached paginator but looks like forgot to cover these pages. We'll fix this soon.

**Comment by djangotestapp** [comment]
Thanks @ialbert and @Natay

**Comment by Natay** [comment]
This issue has been fixed.
