### ISSUE TITLE
celery error No module named 'celery'

### ISSUE THREAD

**Issue by BruceChen2017** [ialbert/biostar-central#737]
When running recipes, e.g. `make recipes serve`, it gives me error message: `celery error No module named 'celery'`. After browsing source code, I think it comes from `biostar/__init__.py`. Though this import error, the site seems to still work well.

**Comment by Natay** [comment]
Thank you for letting us know @BruceChen2017, celery requires an import at package level and the message you see comes from a try/execpet block in biostar/__init__.py. 
We wrap it with try/expect block because celery is not required to run the site, as you have seen. 

We will work to isolate this to the forum.
