### ISSUE TITLE
not found(deploying via digitaloccean, nginx, ubuntu)

### ISSUE THREAD

**Issue by coreydipsy** [ialbert/biostar-central#867]
I tried to deploy the website using digitaloccean and I followed the tutorial it provided:
https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-20-04
Everything works fine until the step of "gunicorn --bind 0.0.0.0:8000 biostar.wsgi"
There is a wsgi.py under Biostar and there are no error messages
<img width="612" alt="Screen Shot 2021-06-20 at 4 05 05 PM" src="https://user-images.githubusercontent.com/56062470/122666665-488d5200-d1e1-11eb-951b-c30c8be820c7.png">; 
however, when I go to the IP address, it told me not found.
<img width="762" alt="Screen Shot 2021-06-20 at 4 06 24 PM" src="https://user-images.githubusercontent.com/56062470/122666686-770b2d00-d1e1-11eb-8f07-9f14ad2b49b5.png">
What should I do to fix this issue? 
Thank you!!!

**Comment by Natay** [comment]
Hey @coreydipsy , this may happen because of many reasons, maybe the nginx is not proxying to gunicorn correctly, but this is a configuration question better fitted for the digital ocean question board.

**Comment by ialbert** [comment]
As @Natay said this is a general Unix webserver deployment issue. It is a frustrating experience to get through a you may have firewalls set up, your local IP numbers may look different than those reported to the world, binding to a specific host or numbers, lower ports can only be bound as a superuser, etc all may cause issues


here do note that you need to also pass the port number, since you are binding to port 8000 so in my first read your problem is that you are not accessing the port number:

128.199.219.3:8000

the best would be to access by domain name,

hostname.com:8000
